---
version: '3.5'

services:
  zookeeper-north:
    image: confluentinc/cp-zookeeper:${TAG}
    hostname: zookeeper-north
    container_name: zookeeper-north
    networks:
      - n1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper-north:2888:3888;zookeeper-central:2888:3888;zookeeper-south:2888:3888

  zookeeper-central:
    image: confluentinc/cp-zookeeper:${TAG}
    hostname: zookeeper-central
    container_name: zookeeper-central
    networks:
      - n1
    depends_on:
      - zookeeper-north
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper-north:2888:3888;zookeeper-central:2888:3888;zookeeper-south:2888:3888

  zookeeper-south:
    image: confluentinc/cp-zookeeper:${TAG}
    hostname: zookeeper-south
    container_name: zookeeper-south
    networks:
      - n1
    depends_on:
      - zookeeper-north
      - zookeeper-central
    ports:
      - "2183:2183"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper-north:2888:3888;zookeeper-central:2888:3888;zookeeper-south:2888:3888

  broker-north-1:
    image: confluentinc/cp-server:${TAG}
    hostname: broker-north-1
    container_name: broker-north-1
    networks:
      - n1
    ports:
      - "9091:9091"
      - "8091:8091"
    volumes:
      - ./config:/etc/kafka/demo
    depends_on:
      - zookeeper-north
      - zookeeper-central
      - zookeeper-south
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: 'north'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-north-1:19091,EXTERNAL://localhost:9091
      KAFKA_REPLICA_SELECTOR_CLASS: org.apache.kafka.common.replica.RackAwareReplicaSelector
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-north:2181,zookeeper-central:2182,zookeeper-south:2183'
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-ccc:19098
      KAFKA_CONFLUENT_MONITORING_INTERCEPTER_BOOTSTRAP_SERVERS: broker-ccc:19098
      KAFKA_JMX_PORT: 8091
      KAFKA_CONFLUENT_LOG_PLACEMENT_CONSTRAINTS: '{"version": 1,"replicas": [{"count": 2, "constraints": {"rack": "north"}}], "observers": [{"count": 2, "constraints": {"rack": "south"}}]}'
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 4
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  broker-north-2:
      image: confluentinc/cp-server:${TAG}
      hostname: broker-north-2
      container_name: broker-north-2
      networks:
        - n1
      ports:
        - "9092:9092"
        - "8092:8092"
      volumes:
        - ./config:/etc/kafka/demo
      depends_on:
        - zookeeper-north
        - zookeeper-central
        - zookeeper-south
        - broker-north-1
      environment:
        KAFKA_BROKER_ID: 2
        KAFKA_BROKER_RACK: 'north'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-north-2:19092,EXTERNAL://localhost:9092
        KAFKA_REPLICA_SELECTOR_CLASS: org.apache.kafka.common.replica.RackAwareReplicaSelector
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-north:2181,zookeeper-central:2182,zookeeper-south:2183'
        KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 2
        KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
        KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-ccc:19098
        KAFKA_CONFLUENT_MONITORING_INTERCEPTER_BOOTSTRAP_SERVERS: broker-ccc:19098
        KAFKA_JMX_PORT: 8092
        KAFKA_CONFLUENT_LOG_PLACEMENT_CONSTRAINTS: '{"version": 1,"replicas": [{"count": 2, "constraints": {"rack": "north"}}], "observers": [{"count": 2, "constraints": {"rack": "south"}}]}'
        KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 4
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  broker-south-3:
      image: confluentinc/cp-server:${TAG}
      hostname: broker-south-3
      container_name: broker-south-3
      networks:
        - n1
      ports:
        - "9093:9093"
        - "8093:8093"
      volumes:
        - ./config:/etc/kafka/demo
      depends_on:
        - zookeeper-north
        - zookeeper-central
        - zookeeper-south
        - broker-north-1
        - broker-north-2
      environment:
        KAFKA_BROKER_ID: 3
        KAFKA_BROKER_RACK: 'south'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-south-3:19093,EXTERNAL://localhost:9093
        KAFKA_REPLICA_SELECTOR_CLASS: org.apache.kafka.common.replica.RackAwareReplicaSelector
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-north:2181,zookeeper-central:2182,zookeeper-south:2183'
        KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 2
        KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
        KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-ccc:19098
        KAFKA_CONFLUENT_MONITORING_INTERCEPTER_BOOTSTRAP_SERVERS: broker-ccc:19098
        KAFKA_JMX_PORT: 8093
        KAFKA_CONFLUENT_LOG_PLACEMENT_CONSTRAINTS: '{"version": 1,"replicas": [{"count": 2, "constraints": {"rack": "north"}}], "observers": [{"count": 2, "constraints": {"rack": "south"}}]}'
        KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 4
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  broker-south-4:
      image: confluentinc/cp-server:${TAG}
      hostname: broker-south-4
      container_name: broker-south-4
      networks:
        - n1
      ports:
        - "9094:9094"
        - "8094:8094"
      volumes:
        - ./config:/etc/kafka/demo
      depends_on:
        - zookeeper-north
        - zookeeper-central
        - zookeeper-south
        - broker-north-1
        - broker-north-2
        - broker-south-3
      environment:
        KAFKA_BROKER_ID: 4
        KAFKA_BROKER_RACK: 'south'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-south-4:19094,EXTERNAL://localhost:9094
        KAFKA_REPLICA_SELECTOR_CLASS: org.apache.kafka.common.replica.RackAwareReplicaSelector
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-north:2181,zookeeper-central:2182,zookeeper-south:2183'
        KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 2
        KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
        KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-ccc:19098
        KAFKA_CONFLUENT_MONITORING_INTERCEPTER_BOOTSTRAP_SERVERS: broker-ccc:19098
        KAFKA_JMX_PORT: 8094
        KAFKA_CONFLUENT_LOG_PLACEMENT_CONSTRAINTS: '{"version": 1,"replicas": [{"count": 2, "constraints": {"rack": "north"}}], "observers": [{"count": 2, "constraints": {"rack": "south"}}]}'
        KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 4
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2


  zookeeper-ccc:
    image: confluentinc/cp-zookeeper:${TAG}
    hostname: zookeeper-ccc
    container_name: zookeeper-ccc
    networks:
      - n1
    ports:
      - "2188:2188"
    environment:
      ZOOKEEPER_SERVER_ID: 4
      ZOOKEEPER_CLIENT_PORT: 2188
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper-ccc:2888:3888


  broker-ccc:
    image: confluentinc/cp-server:${TAG}
    hostname: broker-ccc
    container_name: broker-ccc
    networks:
      - n1
    ports:
      - "9098:9098"
      - "8098:8098"
    volumes:
      - ./config:/etc/kafka/demo
    environment:
      KAFKA_BROKER_ID: 8
      KAFKA_BROKER_RACK: 'metrics'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker-ccc:19098,LISTENER_DOCKER_EXTERNAL://localhost:9098
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-ccc:2188'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-ccc:19098
      KAFKA_JMX_PORT: 8098
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper-ccc

networks:
  n1:
